name: img
base: core18
version: "0.5.7"
summary: Unprivileged Dockerfile & OCI compatible container img builder.
description: |
  Standalone, daemon-less, unprivileged Dockerfile and OCI compatible container image builder.

  - img is more cache-efficient than Docker and can also execute multiple build stages concurrently, as it internally uses BuildKit's DAG solver.
  - The commands/UX are the same as docker {build,tag,push,pull,login,save} so all you have to do is replace docker with img in your scripts, command line, and/or life."
  - Build container images in Kubernetes without mounting in the docker socket or doing anything to compromise the security of your cluster.

  Currently this snap package only has access to the home folder.

  - Full blog article: https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/
  - Snap package issues can be reported at https://github.com/bashfulrobot/snapcrafters-img/issues
confinement: strict
grade: stable
architectures:
  - build-on: amd64
parts:
  img:
    plugin: nil
    build-packages:
      - wget
    stage-packages:
      - uidmap
    override-pull: |
      wget https://github.com/genuinetools/img/releases/download/v$SNAPCRAFT_PROJECT_VERSION/$SNAPCRAFT_PROJECT_NAME-linux-$SNAP_ARCH
    override-build: |
      snapcraftctl build
      install $SNAPCRAFT_PROJECT_NAME-linux-$SNAP_ARCH $SNAPCRAFT_PART_INSTALL/img

apps:
  img:
    command: img
    plugs:
      - home
      - network
